image: circleci/python:3.6.7-jessie

style:
    script:
        - python3 -V
        - pip3 install -r requirements.dev.txt --user
        - export PATH=/home/circleci/.local/bin:$PATH
        - make style-check

unittest:
    script:
        - pip3 install -r requirements.dev.txt -r requirements.txt --user
        - export PATH=/home/circleci/.local/bin:$PATH
        - unzip hpman.zip
        - pip3 install -e ./hpman --user
        - make test
    artifacts:
        paths:
            - htmlcov

doc:
    script:
        - export PATH=/home/circleci/.local/bin:$PATH
        - pip3 install -r requirements.dev.txt --user
        - make doc
    artifacts:
        paths:
            - docs/_build/html


pages:
    stage: deploy
    dependencies:
        - unittest
        - doc
    script:
        - mv docs/_build/html public
        - mv htmlcov public/cov
    artifacts:
        paths:
            - public


release:
    stage: deploy
    dependencies: 
        - unittest
        - doc
    script:
        - export PATH=/home/circleci/.local/bin:$PATH
        - pip3 install -r requirements.dev.txt --user
        - make wheel
        - devpi use "http://192.168.0.195:3141/tanxuehan/dev/+f/15c/add2fcb292e52/hpargparse-0.0.6.tar.gz"
        - devpi login "tanxuehan" --password="951123" && devpi upload dist/*

