image: circleci/python:3.6.7-jessie

style:
    script:
        - python3 -V
        - pip3 install -r requirements.dev.txt --user
        - export PATH=/home/circleci/.local/bin:$PATH
        - make style-check

unittest:
    script:
        - pip3 install -r requirements.dev.txt -r requirements.txt --user
        - export PATH=/home/circleci/.local/bin:$PATH
        - unzip hpman.zip
        - pip3 install -e ./hpman --user
        - make test
    artifacts:
        paths:
            - htmlcov

doc:
    script:
        - pip3 install -r requirements.dev.txt --user
        - export PATH=/home/circleci/.local/bin:$PATH
        - make doc
    artifacts:
        paths:
            - docs/_build/html


pages:
    stage: deploy
    dependencies:
        - unittest
        - doc
    script:
        - mv docs/_build/html public
        - mv htmlcov public/cov
    artifacts:
        paths:
            - public


release:
    stage: deploy
    dependencies: 
        - unittest
        - doc
    script:
        - make wheel
        - devpi use "${DEVPI_URL}" 
        - devpi login "${DEVPI_LOGIN}" --password="${DEVPI_PASSWORD}" && devpi upload dist/*

